name: ovorideuser
description: MeroRides is a complete ride-sharing solution.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+6

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:

  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  coupon_uikit: ^0.2.1
  cupertino_icons: ^1.0.8
  custom_marker_builder: ^0.0.4
  dio: ^5.9.0
  dotted_border: ^3.1.0
  file_picker: ^10.3.3
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.5.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  flutter_widget_from_html: ^0.17.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  google_maps_flutter: ^2.13.1
  google_sign_in: ^7.2.0
  image_picker: ^1.2.0
  flutter_image_compress: ^2.3.0
  in_app_review: ^2.0.11
  intl: ^0.20.2
  just_audio: 0.10.5
  line_icons: ^2.0.3
  logger: ^2.6.2
  lottie: ^3.3.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^5.0.2
  pusher_channels_flutter: ^2.5.0
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  sheet: ^1.0.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  timelines_plus: ^1.0.7
  timezone: ^0.10.1
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  vibration: ^3.1.4
  wakelock_plus: ^1.2.5
  flutter_displaymode: ^0.6.0
  zoom_tap_animation: ^1.1.0

  google_maps_flutter_android: 2.18.2
  signature: ^6.3.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/app_icon.png"
  min_sdk_android: 21

dependency_overrides:
  intl: any
  file_picker: any
  just_audio: any

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/social/
    - assets/images/logo/
    - assets/images/logo/splash_screen.jpg
    - assets/images/map/

    - assets/images/onboard/
    - assets/icon/
    - assets/icon/files/
    - assets/animation/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          weight: 300
          style: italic
